---
#info: Install and setup custom software

- name: Setup a webserver with a website
  hosts: www.webhoster.aa,
  gather_facts: no
  become: true
  tasks:
    - name: Install a webserver
      package:
        update_cache: yes
        name:
          - nginx

    - name: Remove default website
      file:
        path: /var/www/html
        state: absent

    - include_role: name=servermonkey.fastpkg
      vars:
        fpkg_package: webrip-www-idsoftware-com-killer
        fpkg_offline: true
        fpkg_install_dir: "/var/www/html"
        fpkg_extra_opts: "o"